### PR TITLE
Edits to make the code work, and to enhance it a bit

### PR DESCRIPTION
**Pull request by brilang**
I tried the UpgradeAdvisor plugin and it wouldn't run initially. I had to make a couple of edits to the code to get it to run on CF 2016. I also added this.installdir as a variable to point to the installation directory for CFWheels if it's not running in the site root. In my case, this is called "/crm". I'm sure there's a way to grab this programmatically, but I just wanted it to work.

### CODE REVIEW

**Comment by chapmandu** [comment]
Thanks, The idea is great but the default app directory should be root.. Looks like you've left the crm directory as default.

**Comment by brilang** [comment]
Oops. Forgot to remove that! I've updated the code. Do I need to do a new pull request (I'm still learning GitHub)?

**Comment by chapmandu** [comment]
Thanks mate, no you can add commits to a pull request until it's merged..

**Comment by chapmandu** [comment]
Can you confirm that the changes will work on an app in the web root?

**Pull request merged**
